version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "senha#123"
    ports:
      - "5435:5432"
    volumes:
      - /home/developer/curso_crud/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      envoymesh:
        aliases:
          - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "developer@ipiranga"
      PGADMIN_DEFAULT_PASSWORD: "senha#123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      envoymesh:
        aliases:
          - pgadmin
  app:
    build: .
    ports:
    - "8000:8000"
    #read_only: true
    shm_size: 256m
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      envoymesh:
        aliases:
          - app
    environment:
      - WITH_TRACER=true
      - TRACER_HOST=localhost
      - TRACER_PORT=5775
      - TRACER_TOKEN=123
      - FLASK_SUPPORT=true
      - TOKEN=123
      - SERVICE_NAME=template_api
      - REALM=template_api
      - DB_HOSTS='postgresql://postgres:senha#123@postgres:5435/postgres'
networks:
  envoymesh: {}